### PR TITLE
Support user id for get_sections

### PR DESCRIPTION
**Pull request by KTibow**
This allows users w/out admin to get sections.

### CODE REVIEW

**Comment by KTibow** [comment]
Is there any interest in this?

**Review by ErikBoesen — APPROVED** [review]

**Comment by AndrewLester** [comment]
While this does resolve some ambiguity, I believe there is already a `get_user_sections` method here:
https://github.com/ErikBoesen/schoolopy/blob/0e624a4956c5d1c038311b4e11e80d65d410cf6d/schoolopy/main.py#L1912

**Comment by KTibow** [comment]
Got it. Should I close, or remove that, or make that reference this function?

**Comment by AndrewLester** [comment]
I think the other method should be all we need, since it seems like it is related to the methods around it like `get_user_groups`. All of those methods access attributes of a user.

**Comment by KTibow** [comment]
Okay. Is there any way to get this up on read the docs or anything, so it's easier to find? If that happens, it might also be good to put what endpoint it uses in the docstrings, so once you find something in schoology's api docs you can find the right function for it.

**Comment by ErikBoesen** [comment]
We have issue #16 open to create a ReadTheDocs page and we'll try to get to that soon.

**Comment by ErikBoesen** [comment]
For the moment, documentation can be found in the README of this project.

**Comment by KTibow** [comment]
There's lots of stuff in the code that isn't in the README, though.

**Comment by ErikBoesen** [comment]
True. Soon we'll probably be doing some fundamental refactoring of how the library works, so we'll probably take that opportunity to update the docs to be more clear.

**Pull request closed without merging**
