### PR TITLE
New method for obtaining grades

### PR DESCRIPTION
**Pull request by plungerman**
we created a new method for obtain grades based on section_id. the grades API endpoint allows you to further filter the results with GET query name/value pairs for: timestamp, enrollment_id, and assignment_id. in order to take advantage of that, we updated the _get() method to allow for an optional query value that is added after the "limit" name/value pair.

the _get() method could remain unmodified if that limit value were not added there. if you would rather remove the bit where the "limit" GET variable is added to the URL, i'd be happy to go that route as well.

### CODE REVIEW

**Comment by ErikBoesen** [comment]
You have conflicts. There are two duplicate commits in this PR.

**Comment by plungerman** [comment]
hmmm, it says above "This branch has no conflicts with the base branch". strange.

**Comment by ErikBoesen** [comment]
@plungerman Sorry, not literal conflicts, but there are duplicate commits which have already been merged.

**Comment by plungerman** [comment]
huh, not certain how that happened. ok, will have to regroup.

**Comment by ErikBoesen** [comment]
Stale, closing.

**Pull request closed without merging**
